# generated by datamodel-codegen:
#   filename:  vraquery-v1.0.0.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field
from enum import StrEnum
from uuid import UUID


class AdatFajta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Mertekegyseg: str | None = Field(None, description="Adatfajta mértékegység")
    Minimum: float | None = Field(None, description="Legkisbb elfogadható érték")
    Maximum: float | None = Field(None, description="Legnagyobb elfogadható érték")
    Pontossag: int | None = Field(None, description="Adatfajta tizedesjegyeinek száma")
    Nev: str | None = Field(None, description="A kód neve")
    KodSorszam: int | None = Field(None, description="Megjelenítésben sorrendje")
    KodAZ: int | None = Field(None, description="A kód egyedi azonosítója")


class AdatKiseroKod(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    RovidNev: str | None = Field(None, description="A kód rövid megnevezése")
    Jel: str | None = Field(None, description="A kód jele")
    Csoport: str | None = Field(
        None,
        description="A kód csoportja\r\nCSAPJELKOD, DEFAULT, GAZLOHELYKOD, GAZLOINFOKOD, HOKOD, JEGKOD, NEDVESLEGHOMERESKOD,ZSILIPKOD",
    )
    Ervenyes: bool | None = Field(
        None, description="Igaz, ha a kód használatban van, hamis, ha már nem kiosztható"
    )
    Nev: str | None = Field(None, description="A kód neve")
    KodSorszam: int | None = Field(None, description="Megjelenítésben sorrendje")
    KodAZ: int | None = Field(None, description="A kód egyedi azonosítója")


class AdatMinosites(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    KodRov: str | None = None
    Default: bool | None = None
    Nev: str | None = Field(None, description="A kód neve")
    KodSorszam: int | None = Field(None, description="Megjelenítésben sorrendje")
    KodAZ: int | None = Field(None, description="A kód egyedi azonosítója")


class AdatTipus(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    KodCsoportKod: int | None = Field(None, description="Adattípus csoprtja")
    Ervenyes: bool | None = Field(None, description="Az aktuális időponban használható-e")
    Nev: str | None = Field(None, description="A kód neve")
    KodSorszam: int | None = Field(None, description="Megjelenítésben sorrendje")
    KodAZ: int | None = Field(None, description="A kód egyedi azonosítója")


class AggregateRangePositionEnum(StrEnum):
    """
    Aggregáció kiegészítő információja
    none = nincs;
    minmaxpos = Csak minimum és maximum-nál lesz használható. A min max időpontját berakja a DataExt-be
    """

    none = "none"
    minmaxpos = "minmaxpos"


class AggregateRangeTypeEnum(StrEnum):
    """
    Aggregációs időtartam
    none = nincs;
    daily = napi;
    tenday = dekád;
    monthly = havi;
    yearly = éve;
    """

    none = "none"
    daily = "daily"
    tenday = "tenday"
    monthly = "monthly"
    yearly = "yearly"


class AggregateTypeEnum(StrEnum):
    """
    Aggregáció típusa
    min = minimum;
    max = maximum;
    avg = matematikai átlag;
    sum = összeg;
    cnt = darab;
    mean = közép érték, idővel súlyozva;
    cntday = értékes napok száma;
    """

    min = "min"
    max = "max"
    avg = "avg"
    sum = "sum"
    cnt = "cnt"
    mean = "mean"
    cntday = "cntday"


class DailyRangeFindEnum(StrEnum):
    """
    none = A megadott időpont és a tűréshatárt figyelembe véve minden adat
    exacttime= A megadott időponttal egyező adat
    nearestime = A megadott időponthoz legközelebbi adat a türéshatáron belül
    exactinterpol =A megadott időpontra interpolált adat. Az interpoláció lineáris a két alap érték csak a megadott tűréshatáron belül fogadható el.
    nearestinterpol = A megadott időponthoz legközelebbi adat a türéshatáron belül, ha nincs lineárisan interpolál a megadott tűréshatáron belül.
    """

    none = "none"
    exacttime = "exacttime"
    nearestime = "nearestime"
    exactinterpol = "exactinterpol"
    nearestinterpol = "nearestinterpol"


class DataCatalogMinMax(BaseModel):
    """
    A rendelkezésre álló legkorábbi és legkésőbbi adat
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    HAFKod: int | None = Field(None, description="Keresett adatfajta")
    ATKod: int | None = Field(None, description="Keresett adattípus")
    DataExt: int | None = Field(None, description="Kiegészítő adat")
    Torzsszam: int | None = Field(None, description="VMO törzsszáma")
    UTCTimeMin: AwareDatetime | None = Field(
        None,
        description="A VMO legkorábbi adatának időpontja UTC time-ban, az adoott hafkod és atkod-ra",
    )
    UTCTimeMax: AwareDatetime | None = Field(
        None,
        description="A VMO legkésőbbi adatának időpontja UTC time-ban, az adoott hafkod és atkod-ra",
    )


class ForecastItem(BaseModel):
    """
    Előrejelzett adat
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    UTCTime: AwareDatetime | None = Field(
        None, description="Az előrejelzett adat időpontja UTC-ben perc pontossággal"
    )
    UTCTime2: AwareDatetime | None = Field(
        None,
        description="Az előrejelzés második időpontja UTC-ben perc pontossággal, intervallumos előrejelzésnél. Lehet NULL értékű nem intervallumos előrejezés esetén.",
    )
    Adat: float | None = Field(None, description="Az előrejelzett adat (vízállás/vízhozam) értéke")
    Adat2: float | None = Field(
        None,
        description="Az előrejelzett második adat (vízállás/vízhozam) értéke, intervallumos előrejelzés esetén. Lehet NULL értékű nem intervallumos előrejezés esetén.",
    )
    AdatKonf: float | None = Field(None, description="Az előrejelzési konfidencia sáv értéke")
    AdatMax: bool | None = Field(
        None, description="igaz, ha ez tetőző vízállás vagy maximum vízhozam az előrejelzésben"
    )
    DPComment: str | None = Field(
        None,
        description="Az adat (sor) értékéhez fűzött felhasználói feljegyzés.  Adatcsomagon keresztül kap értéket.",
    )


class ISShortItemDT(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Fkm: float | None = Field(
        None,
        description="A szelvényszám, ahol a szakaszon belül a jégjelenséget megfigyelték – a jégadatok a szelvénytől lefelé érvényesek (Fkm)",
    )
    UTCTime: AwareDatetime | None = Field(None, description="Jégmegfigyelés időpontja")
    JegKod1: int | None = Field(
        None, description="Észlelt jégjelenség kódja (1). AKGroup = ’JEGKOD’"
    )
    JegKod2: int | None = Field(
        None, description="Észlelt jégjelenség kódja (2). AKGroup = ’JEGKOD’"
    )
    JegV: int | None = Field(None, description="Az észlelt jég vastagsága (cm)")
    HoJegen: int | None = Field(None, description="A jégen észlelt hó vastagsága (cm)")
    HoKod: int | None = Field(
        None, description="A jégen észlelt hójelenség kódja. AKGroup = ’HOKOD’"
    )


class ISShortResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ItemId: int | None = Field(None, description="Kérésben átadott lista elem azaonosító")
    IsItemList: list[ISShortItemDT] | None = Field(
        None, description="Idősor elemek kérése elemenként"
    )


class InternetVMO(BaseModel):
    """
    Vízrajzi megfigyelő objektum
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    Tsz: int | None = Field(None, description="Objektum vízrajzi törzsszáma")
    Nev: str | None = Field(None, description="Objektum neve")
    Vizig: int | None = Field(None, description="Tulajdonos szervezet (vizig) kódja")
    EOVx: float | None = Field(None, description="Objektum földrajzi EOV koordinátája")
    EOVy: float | None = Field(None, description="Objektum földrajzi EOV koordinátája")
    Uzem: bool | None = Field(None, description="A lekérdezés időpontjában az állomás üzemel-e")
    Lat: float | None = Field(None, description="Objektum földrajzi koordinátája latitude")
    Lon: float | None = Field(None, description="Objektum földrajzi koordinátája longitude")
    Aft: int | None = Field(
        None,
        description=" Adatforgalmazás típusa\r\n KodAZ\tKodSorszam\tNev\r\n4489 ismeretlen\r\n4490 észlelt\r\n4491 regisztrált\r\n4492 távmért\r\n4584 nincs",
    )
    Mdr: UUID | None = Field(None, description="Felszíni állomás kapcsolódó meder")
    Fkm: float | None = Field(None, description="Felszíni állomás szelvényszáma")
    LKV: int | None = Field(None, description="Felszíni állomás esetén legkisebb mért vízállás")
    LNV: int | None = Field(None, description="Felszíni állomás esetén legnagyobb mért vízállás")
    KF1: int | None = Field(None, description="Felszíni állomás esetén elsőfok szintje")
    KF2: int | None = Field(None, description="Felszíni állomás esetén másodfok szintje")
    KF3: int | None = Field(None, description="Felszíni állomás esetén harmadfok szintje")
    Npt: float | None = Field(
        None,
        description="Nullpont: felszíni állomás esetén a mérce nullpontja, felszínközeli és felszín alatti esetén a kútperem magassága",
    )
    MdrNev: str | None = Field(None, description="Felszíni állomás kapcsolódó meder megnevezése.")
    Telepules: str | None = Field(None, description="Kapcsolódó település megnevése")


class InterpolatingModeEnum(StrEnum):
    """
    interpoláció típusa
    """

    linear = "linear"
    spline = "spline"


class LoginResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Token: str | None = None


class LoginUser(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Username: str | None = None
    Password: str | None = None


class MeresIP(BaseModel):
    """
    Reggeli és eseti mérési időpontok
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(None, description="Állomás törzsszáma")
    MeresPerc: int | None = Field(
        None, description="Mérési időpontja 0 órától percben helyi idő szerint"
    )
    IdopontUTC: AwareDatetime | None = Field(None, description="Az adat érvényességének kezdete")
    Reggel: bool | None = Field(None, description="Reggeli, vagy esti adat időpontja-e a rekord")


class MezoMinosites(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Jel: str | None = Field(None, description="A minősítés jele")
    Csoport: int | None = Field(None, description="Minősítés csoportosítása")
    Default: bool | None = Field(None, description="Alpértelmezett minősítés")
    Nev: str | None = Field(None, description="A kód neve")
    KodSorszam: int | None = Field(None, description="Megjelenítésben sorrendje")
    KodAZ: int | None = Field(None, description="A kód egyedi azonosítója")


class TSFullItemDT(BaseModel):
    """
    Minden adatot tartalmazó szerkezet
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    AFKod: int | None = Field(None, description="Adatforrás kódja")
    DPUserID: int | None = Field(None, description="Felhasználó azonosítója")
    DPTime: AwareDatetime | None = Field(None, description="Módosítás időpontja")
    DPComment: str | None = Field(None, description="Megjegyzés")
    tsID: int | None = Field(None, description="Rekord azonosítója a tároló partíción belül")
    AKKod: int | None = Field(None, description="Adatkisérőkód")
    MMKod: int | None = Field(None, description="Mezőminősító kód")
    AMKod: int | None = Field(None, description="Adatminősítő kód")
    UTCTime: AwareDatetime | None = Field(None, description="Adat időpontja UTC-ben")
    Adat: float | None = Field(None, description="Adat értéke")
    DataExt: int | None = Field(0, description="Kiegészítő adat")


class TSFullItemDTTSResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(None, description="Az adott kérésen belül a törzsszám")
    TsItemList: list[TSFullItemDT] | None = Field(
        None, description="Az adott kérésen belül a törzsszámhoz tartozó eredmény lista"
    )


class TSLongItemDT(BaseModel):
    """
    Minősítő kódokat is tartalmazó idősor
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    AKKod: int | None = Field(None, description="Adatkisérőkód")
    MMKod: int | None = Field(None, description="Mezőminősító kód")
    AMKod: int | None = Field(None, description="Adatminősítő kód")
    UTCTime: AwareDatetime | None = Field(None, description="Adat időpontja UTC-ben")
    Adat: float | None = Field(None, description="Adat értéke")
    DataExt: int | None = Field(0, description="Kiegészítő adat")


class TSLongItemDTTSResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(None, description="Az adott kérésen belül a törzsszám")
    TsItemList: list[TSLongItemDT] | None = Field(
        None, description="Az adott kérésen belül a törzsszámhoz tartozó eredmény lista"
    )


class TSLongResponse(BaseModel):
    """
    Minősítő kódokat is tartalmazó eredményhalmaz
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ItemId: int | None = Field(None, description="Kérésben átadott lista elem azaonosító")
    TsItemList: list[TSLongItemDT] | None = Field(
        None, description="Idősor elemek kérése elemenként"
    )


class TSShortItemDT(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    UTCTime: AwareDatetime | None = Field(None, description="Adat időpontja UTC-ben")
    Adat: float | None = Field(None, description="Adat értéke")
    DataExt: int | None = Field(0, description="Kiegészítő adat")


class TSShortItemDTTSResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(None, description="Az adott kérésen belül a törzsszám")
    TsItemList: list[TSShortItemDT] | None = Field(
        None, description="Az adott kérésen belül a törzsszámhoz tartozó eredmény lista"
    )


class TSShortResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ItemId: int | None = Field(None, description="Kérésben átadott lista elem azaonosító")
    TsItemList: list[TSShortItemDT] | None = Field(
        None, description="Idősor elemek kérése elemenként"
    )


class ValueFilterEnum(StrEnum):
    """
    Állomások adatkonverziója szintek alapján
    Relativ = Eredeti érték a mérés, vagy leolvasás nullpontjához viszonyítottan.;
    Balti = Az egység méter a vízszint a mBf értékben;
    Terep = A mindenkori terepszinthez viszonyítottan. Csak kútnál értelmezett talajvíznél cm, rétegvíznél m egységben
    UtolsoNullpont = Az utolsó kútperem magassághoz viszonyítottan. Csak felszín alatti állomásoknál értelmezett
    """

    Relativ = "Relativ"
    Balti = "Balti"
    Terep = "Terep"
    UtolsoNullpont = "UtolsoNullpont"


class Vmo(BaseModel):
    """
    Vízrajzi megfigyelési objektum
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(None, description="Objektum vízrajzi törzsszáma")
    Nev: str | None = Field(None, description="Objektum neve")
    TipusKod: int | None = Field(None, description="VMO típuskód pl felszíni, hidromet...")
    SzervezetKod: int | None = Field(None, description="Tulajdonso szervezet kódja")
    EOVx: float | None = Field(None, description="Objektum földrajzi EOV koordinátája")
    EOVy: float | None = Field(None, description="Objektum földrajzi EOV koordinátája")
    Uzemel: bool | None = Field(None, description="A lekérdezés időpontjában az állomás üzemel-e")


class AggregateFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    RangeType: AggregateRangeTypeEnum | None = None
    AggregateType: AggregateTypeEnum | None = None
    AggregateRangePosition: AggregateRangePositionEnum | None = None
    MaxNullDayCount: int | None = Field(
        None,
        description="Az időszakban megengedett maximális üres nap, null esetén bármennyi lehet",
    )
    MaxNullDayRangeLengh: int | None = Field(
        None,
        description="Az időszakban megengedett olyan szakasz hossza napban, ahol egymás utáni napon nincs adat. Null esetén bármennyi lehet.",
    )


class DailyFilter(BaseModel):
    """
    Napon belüli szűrő időpont alapján
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    CenterMin: list[int] | None = Field(
        None, description="Elvárt időpont 0 órától percben lehet több idő is pl reggel és este"
    )
    RangeMin: int | None = Field(None, description="Tűréshatár +- percben")
    DailyRangeFind: DailyRangeFindEnum | None = None
    NearestInterpolRangeMin: int | None = Field(
        None,
        description="Legközelebbi pótlással keresésnél az interpolációs intervallum +- percben",
    )
    InterpolatingMode: InterpolatingModeEnum | None = None


class RequestIS(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    Torzsszam: int | None = Field(
        None, description="Keresett VMO törzsszáma, felszíni állomás, vagy jégjelentő szakasz"
    )
    AdatTipusKod: int | None = Field(None, description="ATKod, adattípus kód")
    StartTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok kezdete")
    EndTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok vége")
    DailyFilters: DailyFilter | None = None


class RequestISList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    TorzsszamList: list[int] | None = Field(
        None, description="Keresett VMO törzsszámalista, felszini állomás vagy jégjelentő szakasz"
    )
    AdatTipusKod: int | None = Field(None, description="ATKod, adattípus kód")
    StartTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok kezdete")
    EndTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok vége")
    DailyFilters: DailyFilter | None = None


class RequestTS(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ItemId: int | None = Field(
        None,
        description="A kérésen belüli sorszám a responseban erre való hivatkozással jön vissza adat",
    )
    Torzsszam: int | None = Field(None, description="Keresett VMO törzsszáma")
    AdatFajtaKod: int | None = Field(None, description="HAFKOD, adatfajtakód")
    AdatTipusKod: int | None = Field(None, description="ATKod, adattípus kód")
    StartTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok kezdete")
    EndTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok vége")
    DataExtFilter: int | None = Field(
        None, description="DataExt mezűben szereplő érték null esetén nincs szűrés"
    )
    DailyFilters: DailyFilter | None = None
    AggregateFilters: AggregateFilter | None = None
    ValueFilter: ValueFilterEnum | None = None


class RequestTSList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    TorzsszamList: list[int] | None = Field(None, description="Keresett VMO törzsszámalista")
    AdatFajtaKod: int | None = Field(None, description="HAFKOD, adatfajtakód")
    AdatTipusKod: int | None = Field(None, description="ATKod, adattípus kód")
    StartTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok kezdete")
    EndTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok vége")
    DataExtFilter: int | None = Field(
        None, description="DataExt mezűben szereplő érték null esetén nincs szűrés"
    )
    DailyFilters: DailyFilter | None = None
    AggregateFilters: AggregateFilter | None = None
    ValueFilter: ValueFilterEnum | None = None
    AMKodFilter: list[int] | None = Field(
        None,
        description="Az eredmény halmazban csak azok a sorok lesznek figyelembevéve, melyek adatminősítő kódja a listában szerepel, ha nincs elem a listában akkor az összes, csak long lekérdezéssel együtt szűr",
    )


class TSFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    FilterID: int | None = Field(
        None, description="A kérés egyedi azonosítója, egy requesten belül egyedinek kell lenni"
    )
    AdatFajtaKod: int | None = Field(None, description="HAFKOD, adatfajtakód")
    AdatTipusKod: int | None = Field(None, description="ATKod, adattípus kód")
    StartTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok kezdete")
    EndTime: AwareDatetime | None = Field(None, description="Legyűjtendő adatok vége")
    DataExtFilter: int | None = Field(
        None, description="DataExt mezűben szereplő érték null esetén nincs szűrés"
    )
    DailyFilters: DailyFilter | None = None
    AggregateFilters: AggregateFilter | None = None
    ValueFilter: ValueFilterEnum | None = None
    AMKodFilter: list[int] | None = Field(
        None,
        description="Az eredmény halmazban csak azok a sorok lesznek figyelembevéve, melyek adatminősítő kódja a listában szerepel, ha nincs elem a listában akkor az összes, csak long lekérdezéssel együtt szűr",
    )


class TSFullItemDTResponseTSListFilter(BaseModel):
    """
    Szűrt eredmény halmaz
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    FilterID: int | None = Field(
        None, description="A kérés egyedi azonosítója, egy requesten belül egyedinek kell lenni"
    )
    FilteredResponse: list[TSFullItemDTTSResponse] | None = Field(
        None, description="A kéréshez tartozó eredmény halmazok"
    )


class TSLongItemDTResponseTSListFilter(BaseModel):
    """
    Szűrt eredmény halmaz
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    FilterID: int | None = Field(
        None, description="A kérés egyedi azonosítója, egy requesten belül egyedinek kell lenni"
    )
    FilteredResponse: list[TSLongItemDTTSResponse] | None = Field(
        None, description="A kéréshez tartozó eredmény halmazok"
    )


class TSShortItemDTResponseTSListFilter(BaseModel):
    """
    Szűrt eredmény halmaz
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    FilterID: int | None = Field(
        None, description="A kérés egyedi azonosítója, egy requesten belül egyedinek kell lenni"
    )
    FilteredResponse: list[TSShortItemDTTSResponse] | None = Field(
        None, description="A kéréshez tartozó eredmény halmazok"
    )


class RequestTSListFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    TorzsszamList: list[int] | None = Field(
        None, description="Az adott törzsszámlistára minden fileterre lehajtja a lekérdezést"
    )
    Filters: list[TSFilter] | None = Field(None, description="Szűrési feltételek listája")
